name: disaster-alerts
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - flask
  - pydantic
  - pyyaml
  - requests
  - geopandas
  - pytest
  - shapely
  - folium
  - pip
  - asf_search
  - beautifulsoup4
  - boto3
  - earthaccess
  - jupyterlab
  - leafmap
  - lxml
  - gdal
  - rasterio
  - tabulate
  - openpyxl>=3.1.0
  - timezonefinder
  - matplotlib
  - numpy
  - pandas
  - pyproj
  - pygmt
  - rioxarray<0.20.0
  - xarray
  - click
  - pip:
      - yagmail
      - next-pass
      - opera-utils
      - git+https://github.com/OPERA-Cal-Val/disasters.git@main
